### PR TITLE
Archive Tasks Feature

### PR DESCRIPTION
**Pull request by rishabhdeepsingh**
Feature- Archive any task #120
- Custom directory
- Custom fileName

PS: Sorry, my laptop was broken that's why it got a little late.

### CODE REVIEW

**Comment by AlexeyDmitriev** [comment]
Hi,

Let's discuss they use case you are trying to solve and understand whether it solves it and whether there's a better solution for that use case.
As far as I understand the code, it just creates a copy of the inlined file (i.e file to submit). It seems you can't continue development afterwards, so I am not sure I understand how it's going to be used

**Comment by rishabhdeepsingh** [comment]
Let's say you created a class (ex. segment tree) but you want to see how it is implemented for finding sum or minimum or other queries. So you might want to save it as a copy of the code so as to come back later as a reference to the same code.
It might not be useful for you. but for a beginner, it will be really very helpful.

**Comment by AlexeyDmitriev** [comment]
I understand that you find it helpful, an it might as well be, I just want to understand your use case better, because for what you described so far it looks like there solution that doesn't require coding from you and also more convenient to use for you and other people.

So, please tell more about how you are going to use it, so I have several questions and may be you can add something to them:
1) In your usecase, are you not going to rerun the problem after you return to it? Just read/copy the code?
2) Are you going to archive all/most problems to return as needed or just some problems where you know there's something useful
3) Are you going to leave problems in archive indefinitely or till you are act on it somehow (e.g. when you extract the code to your library)?
4) Are you speaking more about problems from the contests or mainly concerned with the problems from upsolving/archive where you know that you are implementing.

Also as implemented, is archive more convenient to use than just copy file output.cpp (i.e if you click ⌘C, ⌘V when chosing file in project treem you get the dialog which allow to set the name, has the list of recently used destinations, file chooser dialog, etc, also you can choose directory where to copy by finding it in the project tree) https://youtu.be/3lfLxJY4kbM

**Comment by rishabhdeepsingh** [comment]
1. I mean after a few months. It might be useful to see how did we implement something and or go thought the problem again. one can just add a comment to which problem the task belongs to.
2. Only a few problems where there is a new DS used or any other functionality that I should take care of next time for similar problems.
3. Well, it depends on how others are going to use as well (every code for example segment tree can be converted to a template). so It depends on the user.
4. It is just a quick way to archive so that we don't have to copy-paste and run every task again to check it the output is the same. One can just archive to the directory that the task belongs to.
Overall it depends mostly on the user how he/she uses the feature.

**Comment by AlexeyDmitriev** [comment]
I'm asking about you personally now

**Comment by rishabhdeepsingh** [comment]
Implement something new That I don't know before. Then archive that task for a future reference.

**Comment by rishabhdeepsingh** [comment]
any updates?

**Comment by rishabhdeepsingh** [comment]
Closing this as @AntKirill did a much better job here.

**Pull request closed without merging**
